### ISSUE TITLE
I would like to be part of this project

### ISSUE THREAD

**Issue by Dylan144GT** [PocketPilot/PocketPilot#1]
Hi Mirko,

I would like to be part of this project. Would it be possible to share gerber files of latest PCB so that I can make it? I would like to give feedback and contribute.

If you have any questions for me please let me know and I'll do my bast to answer them.

Thanks,

Dylan

**Comment by shervinemami** [comment]
Hi Dylan, good to hear :-) Join the chat forum at https://gitter.im/mirkix/BBBMINI. A commercial pocket version is getting worked on by a manufacturing company, but you are definitely free to make your own version. A few of us started designing one but then put it on hold because of lack of time (on my side) + news of the commercial version. But i still think the community will appreciate a DIY version of PocketPilot
